name: Extract code and references from GameCube games.

on:
  push:
    branches:
      - "**"  # Runs on every commit on any branch 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} 
  cancel-in-progress: true

jobs:
  download_extract_list:
    runs-on: ubuntu-latest
        
    - name: Setup env
      run: |
        export $(dbus-launch)
        echo "DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS" >> $GITHUB_ENV
        export XDG_RUNTIME_DIR=/tmp/runtime-user
        mkdir -p $XDG_RUNTIME_DIR
        chmod 700 $XDG_RUNTIME_DIR
        echo "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR" >> $GITHUB_ENV

    steps:
    - name: Prepare
      run: |
        sudo apt-get update && sudo apt-get install -y p7zip-full
        sudo apt install flatpak
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install flathub org.DolphinEmu.dolphin-emu -y
        flatpak-spawn --host webbrowser-app
        
    - name: Downloads & Extracts
      run: |
        echo " # Starting, download index.html ..."
        mkdir -p tmp
        wget -q https://myrient.erista.me/files/Redump/Nintendo%20-%20GameCube%20-%20NKit%20RVZ%20%5Bzstd-19-128k%5D/
        export link_prefix="https://myrient.erista.me/files/Redump/Nintendo%20-%20GameCube%20-%20NKit%20RVZ%20%5Bzstd-19-128k%5D"
        echo " # OK, now index for filenames, download and process everything ..."
        cat index.html | grep .zip | sed 's/\" title.*//' | sed 's/.*href=\"//' | while read -r zip_file; do
          echo " >> Downloading '$(echo "$zip_file" | sed -E '
            s/%20/ /g;  s/%21/!/g;  s/%22/"/g;  s/%23/#/g;  s/%24/\$/g;
            s/%25/%/g;  s/%26/\&/g;  s/%27/'\''/g;  s/%28/(/g;  s/%29/)/g;
            s/%2A/*/g;  s/%2B/+/g;  s/%2C/,/g;  s/%2D/-/g;  s/%2E/./g;
            s/%2F/\//g; s/%3A/:/g;  s/%3B/;/g;  s/%3C/</g;  s/%3D/=/g;
            s/%3E/>/g;  s/%3F/?/g;  s/%40/@/g;  s/%5B/[/g;  s/%5C/\\/g;
            s/%5D/]/g;  s/%5E/^/g;  s/%5F/_/g;  s/%60/`/g;  s/%7B/{/g;
            s/%7C/|/g;  s/%7D/}/g;  s/%7E/~/g;
          ')'" && \
          wget -q "$link_prefix/$zip_file" && \
          filename=$(ls *.zip | head -n 1) && \
          file_name="${filename%.zip}" && \
          mkdir "$file_name" && \
          echo " # Extracting download ..." && \
          7z x "$filename" -y -bso0 -bsp0 -bse0 && \
          rm "$filename" && \
          rvz_file=$(ls *.rvz | head -n 1) && \
          echo " # Extracting game ..." && \
          flatpak run --command="dolphin-tool" --filesystem=host org.DolphinEmu.dolphin-emu extract -i "$rvz_file" -o "$file_name/" -q && \
          rm "$rvz_file" && \
          cd "$file_name" && \
          echo " # Filter data ..." && \
          find . -type f -iname "*dbg*" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*debug*" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.map*" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.rel*" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.elf*" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.txt*" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.dol*" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.ini*" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.sym*" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.rsym*" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.lua*" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.rso*" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.csv*" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.gci*" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.sav*" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.bat" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.sh" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.xml*" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.s" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.c" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.h" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.cpp" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.hpp" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.o" -exec mv "{}" "../tmp/" \; && \
          find . -type f -iname "*.*log*" -exec mv "{}" "../tmp/" \; && \
          find . -type f \( -iname "*.tgc*" -o -iname "*.gcm*" -o -iname "*.iso*" \) | while read -r tgc_file; do
              echo " > Found sub-archive: '$tgc_file'" && \
              sub_file_name="${tgc_file%.tgc}" && \
              mkdir "../tmp/$sub_file_name" && \
              mkdir "$sub_file_name" && \
              echo "  # Extracting sub game ..." && \
              flatpak run --command="dolphin-tool" --filesystem=host org.DolphinEmu.dolphin-emu extract -i "$tgc_file" -o "$sub_file_name" -q && \
              rm "$tgc_file" && \
              echo "  # Filter sub data ..." && \
              find "$sub_file_name" -type f -iname "*dbg*" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*debug*" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.map*" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.rel*" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.elf*" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.txt*" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.dol*" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.sym*" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.rsym*" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.lua*" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.rso*" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.csv*" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.gci*" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.sav*" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.bat" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.sh" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.s" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.c" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.cpp" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.h" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.hpp" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.o" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.xml*" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.*log*" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              find "$sub_file_name" -type f -iname "*.ini*" -exec mv "{}" "../tmp/$sub_file_name/" \; && \
              echo "  < Finished '$file_name/$sub_file_name', found:" && \
              ls $sub_file_name -m
          done && \
          echo " << Finished '$file_name', ignored types:" && \
          find . -type f | awk -F. '{if (NF>1) print $NF}' | sort -u | paste -sd "," -
          rm -rf ./* && \
          mv ../tmp/* . && \
          rm ../tmp/* -f && \
          rm *lang* *locale* -f && \
          cd .. && \
          echo "    Found:" && \
          ls "$file_name" -m
        done

    - name: Compress
      if: success()  # Only list contents if extraction succeeded
      run: |
        7z a -v4900M BundleGC.7z ./*
        sudo rm -rf ./*/

    - name: Upload file list
      uses: actions/upload-artifact@v4
      with:
        name: BundleGC
        path: BundleGC.7z.*
