name: Download, Extract, and List Contents of 7z File

on:
  workflow_dispatch:

jobs:
  download_extract_list:
    runs-on: ubuntu-latest

    steps:
    - name: Prepare
      run: |
        sudo apt-get update && sudo apt-get install -y p7zip-full
        sudo apt install flatpak
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install flathub org.DolphinEmu.dolphin-emu -y

    - name: Downloads & Extracts
      run: |
        mkdir -p tmp
        wget https://myrient.erista.me/files/Redump/Nintendo%20-%20GameCube%20-%20NKit%20RVZ%20%5Bzstd-19-128k%5D/
        export link_prefix="https://myrient.erista.me/files/Redump/Nintendo%20-%20GameCube%20-%20NKit%20RVZ%20%5Bzstd-19-128k%5D"
        
        cat index.html | grep .zip | sed 's/\" title.*//' | sed 's/.*href=\"//' | while read -r zip_file; do
            echo "$zip_file" && \
            wget -q "$link_prefix/$zip_file" && \
            filename=$(ls *.zip | head -n 1) && \
            file_name="${filename%.zip}" && \
            mkdir "$file_name" && \
            7z x "$filename" && rm "$filename" && \
            rvz_file=$(ls *.rvz | head -n 1) && \
            echo ENTERING DIRECTORY! && \
            cd "$GITHUB_WORKFLOW/$file_name" && \
            dir=$GITHUB_WORKFLOW && \
            echo $dir && \
            ls "$dir" -lha && \
            ls "$dir/$file_name" -lha && \
            flatpak run --command="dolphin-tool" org.DolphinEmu.dolphin-emu extract -i "$dir/$rvz_file" -o "$dir/$file_name/" && \
            echo DONE EXTRACT! && \
            ls -lha && \
            ls ../ -lha && \
            rm "../$rvz_file" && \
            echo THIS IS ABOUT TO MOVE! && \
            find . -type f -name "*dbg*" -exec mv {} ../tmp/ \; && \
            find . -type f -name "*debug*" -exec mv {} ../tmp/ \; && \
            find . -type f -name "*.map" -exec mv {} ../tmp/ \; && \
            find . -type f -name "*.rel" -exec mv {} ../tmp/ \; && \
            find . -type f -name "*.elf" -exec mv {} ../tmp/ \; && \
            find . -type f -name "*.txt" -exec mv {} ../tmp/ \; && \
            find . -type f -name "*.ini" -exec mv {} ../tmp/ \; && \
            echo THIS HAS MOVED! && \
            ls -lha && \
            sudo rm -rf ./* && \
            cd .. && \
            mv tmp/* "$file_name"/ && \
            ls "$file_name"
        done

    - name: Compress
      if: success()  # Only list contents if extraction succeeded
      run: |
        7z a BundleGC.7z ./*
        sudo rm -rf ./*/

    - name: Upload file list
      if: success()  # Only upload if previous steps succeeded
      uses: actions/upload-artifact@v4
      with:
        name: BundleGC
        path: BundleGC.7z
