name: Download, Extract, and List Contents of 7z File

on:
  workflow_dispatch:

jobs:
  download_extract_list:
    runs-on: ubuntu-latest

    steps:
    - name: Prepare
      run: |
        sudo apt-get update && sudo apt-get install -y p7zip-full
        sudo apt install flatpak
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install flathub org.DolphinEmu.dolphin-emu -y

    - name: Downloads & extract
      run: |
        wget https://myrient.erista.me/files/Redump/Nintendo%20-%20GameCube%20-%20NKit%20RVZ%20%5Bzstd-19-128k%5D/
        export link_prefix="https://myrient.erista.me/files/Redump/Nintendo%20-%20GameCube%20-%20NKit%20RVZ%20%5Bzstd-19-128k%5D"
        cat index.html | grep .zip | sed 's/\" title.*//' | sed 's/.*href=\"//'  | sed 's/.*href=\"//' | while read -r zip_file; do
            echo "$zip_file" && \
            wget -q "$link_prefix/$zip_file" && \
            file_name="${zip_file%.zip}" && \
            7z x "$zip_file" && rm "$zip_file" && \
            rvz_file=$(ls *.rvz 2>/dev/null) && \
            if [ -z "$rvz_file" ]; then echo "No RVZ file found."; exit 1; fi && \
            file_name="${rvz_file%.rvz}" && \
            ls && \
            flatpak run --command="dolphin-tool extract -i \"$rvz_file\" -o \"$file_name/\"" org.DolphinEmu.dolphin-emu && \
            cd "$file_name" && \
            find . -type f \( -iname "*.map" -o -iname "*.rel" -o -iname "*.elf" -o -iname "*.txt" \) -exec mv {} . \; && \
            sudo rm -rf ./*/ && \
            mkdir sys files && \
            mv main.dol sys/ && \
            mv ./*.* files/ && \
            find . && \
            cd ..
        done
    - name: List extracted contents
      if: success()  # Only list contents if extraction succeeded
      run: |
        find . > file_list.txt

    - name: Upload file list
      if: success()  # Only upload if previous steps succeeded
      uses: actions/upload-artifact@v4
      with:
        name: file-list
        path: file_list.txt
