name: Download, Extract, and List Contents of 7z File

on:
  workflow_dispatch:

jobs:
  download_extract_list:
    runs-on: ubuntu-latest

    steps:
    - name: Prepare
      run: |
        sudo apt-get update && sudo apt-get install -y p7zip-full
        sudo apt install flatpak
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install flathub org.DolphinEmu.dolphin-emu -y

    - name: Downloads & extract
      run: |
        wget https://myrient.erista.me/files/Redump/Nintendo%20-%20GameCube%20-%20NKit%20RVZ%20%5Bzstd-19-128k%5D/
        export link_prefix="https://myrient.erista.me/files/Redump/Nintendo%20-%20GameCube%20-%20NKit%20RVZ%20%5Bzstd-19-128k%5D"
        cat index.html | grep .zip | sed 's/\" title.*//' | sed 's/.*href=\"//' | xargs -I{} sh -c 'echo {}; wget -q "$link_prefix/{}"' | export file_name=$(ls *.zip) | export file_name="${file_name%.zip}" | 7z x "$file_name.zip" | rm *.zip | export file_name=$(ls *.rvz) | export file_name="${file_name%.rvz}" | ls | flatpak run --command="dolphin-tool extract -i \"$file_name.rvz\" -o \"$file_name/\"" org.DolphinEmu.dolphin-emu | cd $file_name | find . \( -name "*.map" -o -name "*.rel" -o -name "*.elf" -o -name "*.txt" \) -exec mv {} . \; | sudo rm -rf ./*/ | mkdir sys | mkdir files | mv main.dol sys | mv ./*.* files | find . | cd ..

    - name: List extracted contents
      if: success()  # Only list contents if extraction succeeded
      run: |
        find . > file_list.txt

    - name: Upload file list
      if: success()  # Only upload if previous steps succeeded
      uses: actions/upload-artifact@v4
      with:
        name: file-list
        path: file_list.txt
