name: Download, Extract, and List Contents of 7z File

on:
  workflow_dispatch:

jobs:
  download_extract_list:
    runs-on: ubuntu-latest

    steps:
    - name: Prepare
      run: sudo apt-get update && sudo apt-get install -y p7zip-full dolphin-emu

    - name: Downloads & extract
      run: |
        wget https://myrient.erista.me/files/Redump/Nintendo%20-%20GameCube%20-%20NKit%20RVZ%20%5Bzstd-19-128k%5D/
        export link_prefix="https://myrient.erista.me/files/Redump/Nintendo%20-%20GameCube%20-%20NKit%20RVZ%20%5Bzstd-19-128k%5D"
        cat index.html | grep .zip | sed 's/\" title.*//' | sed 's/.*href=\"//' | xargs -I{} sh -c 'echo {}; wget -q "$link_prefix/{}"; 7z x *.zip; rm *.zip'

    - name: List extracted contents
      if: success()  # Only list contents if extraction succeeded
      run: |
        find . > file_list.txt

    - name: Upload file list
      if: success()  # Only upload if previous steps succeeded
      uses: actions/upload-artifact@v4
      with:
        name: file-list
        path: file_list.txt
