name: Download, Extract, and List Contents of 7z File

on:
  workflow_dispatch:

jobs:
  download_extract_list:
    runs-on: ubuntu-latest

    steps:
    - name: Prepare
      run: |
        sudo apt-get update && sudo apt-get install -y p7zip-full
        sudo apt install flatpak
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install flathub org.DolphinEmu.dolphin-emu -y

    - name: Downloads & extract
      run: |
        mkdir tmp
        wget https://myrient.erista.me/files/Redump/Nintendo%20-%20GameCube%20-%20NKit%20RVZ%20%5Bzstd-19-128k%5D/
        export link_prefix="https://myrient.erista.me/files/Redump/Nintendo%20-%20GameCube%20-%20NKit%20RVZ%20%5Bzstd-19-128k%5D"
        cat index.html | grep .zip | sed 's/\" title.*//' | sed 's/.*href=\"//'  | sed 's/.*href=\"//' | while read -r zip_file; do
            echo "$zip_file" && \
            wget -q "$link_prefix/$zip_file" && \
            file_name="${*%.zip}" && \
            find *.zip && \
            7z x *.zip && rm *.zip && \
            file_name="${*%.rvz}" && \
            ls && \
            rvz_file=$(ls *.rvz)  
            flatpak run --command="dolphin-tool" org.DolphinEmu.dolphin-emu extract -i "$PWD/$rvz_file" -o "$PWD/$file_name/"
            rm *.rvz
            cd "$file_name" && \
            find . -type f \( -o -iname "*dbg*" -o -iname "*debug*" -o -iname "*Dbg*" -o -iname "*Debug*" -o -iname "*DBG*" -o -iname "*DEBUG*" -o -iname "*.map" -o -iname "*.rel" -o -iname "*.elf" -o -iname "*.txt" -o -iname "*.ini" -o -iname "*.MAP" -o -iname "*.REL" -o -iname "*.ELF" -o -iname "*.TXT" -o -iname "*.INI" -o -iname "*.Map" -o -iname "*.Rel" -o -iname "*.Elf" -o -iname "*.Txt" -o -iname "*.Ini" \) -exec mv {} ../tmp \; && \
            sudo rm -rf ./* && \
            mv ../tmp/* . \
            find . && \
            cd ..
        done
        find .
    - name: Compress
      if: success()  # Only list contents if extraction succeeded
      run: |
        7z a BundleGC.7z ./*
        sudo rm ./*/ -rf

    - name: Upload file list
      if: success()  # Only upload if previous steps succeeded
      uses: actions/upload-artifact@v4
      with:
        name: BundleGC
        path: BundleGC.7z
