name: Download, Extract, and List Contents of 7z File

on:
  workflow_dispatch:

jobs:
  download_extract_list:
    runs-on: ubuntu-latest

    steps:
    - name: Prepare
      run: |
        sudo apt-get update && sudo apt-get install -y p7zip-full
        sudo apt update
        sudo apt install -y \
          build-essential \
          cmake \
          git \
          libalut-dev \
          libbluetooth-dev \
          libcurl4-openssl-dev \
          libevdev-dev \
          libglew-dev \
          libopenal-dev \
          libsdl2-dev \
          libsfml-dev \
          libudev-dev \
          qtbase5-dev \
          qtchooser \
          qt5-qmake \
          qtbase5-dev-tools \
          libxi-dev \
          libxrandr-dev \
          libxinerama-dev \
          libudev-dev \
          liblzma-dev \
          libx264-dev \
          lib

        git clone https://github.com/dolphin-emu/dolphin.git
        cd dolphin
        mkdir build && cd build
        cmake .. && make -j4
        sudo make install
        cd ..
        cd ..
        sudo rm -rf dolphin
        dolphin-tool --help

    - name: Downloads & extract
      run: |
        wget https://myrient.erista.me/files/Redump/Nintendo%20-%20GameCube%20-%20NKit%20RVZ%20%5Bzstd-19-128k%5D/
        export link_prefix="https://myrient.erista.me/files/Redump/Nintendo%20-%20GameCube%20-%20NKit%20RVZ%20%5Bzstd-19-128k%5D"
        cat index.html | grep .zip | sed 's/\" title.*//' | sed 's/.*href=\"//' | xargs -I{} sh -c 'echo {}; wget -q "$link_prefix/{}"; export file_name=$(ls *.zip); export file_name="${file_name%.zip}"; 7z x "$file_name.zip"; rm *.zip; dolphin-tool extract -i *.rvz -o "$file_name/"; ls'

    - name: List extracted contents
      if: success()  # Only list contents if extraction succeeded
      run: |
        find . > file_list.txt

    - name: Upload file list
      if: success()  # Only upload if previous steps succeeded
      uses: actions/upload-artifact@v4
      with:
        name: file-list
        path: file_list.txt
